spring:
  datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:postgresql://ec2-44-213-228-107.compute-1.amazonaws.com/dflo2kfif1e4rp
    username: zymqjchvnmhcto
    password: b501dd15f57c7af17eb879b4138a9552b6f0d2e13fb8b6e0acdc9acd5bef81da
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
  sql:
    init:
      platform: postgres
      mode: always